3 columns cards
Semillero-Sincosoft/Workouts pull request #15
Opened 2023-02-22 22:06 UTC by Santiago1R

Primer ejercicio terminado.
- Se me complico poder darle el border-radius al contenedor padre de las tres cards. se solucionó usando uverflow: hidden /atento a comentarios/
-  Envié el ejercicio con la tipografía de los p mas gruesa a como se debe de ver en comparación con el diseño. /atento a posibles formas de solucionarlo/

2023-02-24 16:45 UTC, Santiago1R commented
.

2023-02-28 00:45 UTC, reidid commented
no entiendo muy bien lo que indica del border radious y que se soluciona con overflow hidden, son dos propiedades diferentes una se usa para redondear las esquinas y el otro se usa para que el scroll se visible cuando el contenido supera el tamaño del contenedor

2023-02-28 00:46 UTC, reidid requested changes
Porfa haga las correcciones según los comentarios, en general es que los estilos apliquen para las 3 tarjetas creando clases genéricas por ejemplo card, y las variaciónes si se asignan a los elementos, porque no hay necesidad de repetir las propiedades para cada tarjeta

2023-02-28 00:46 UTC, reidid commented on NEWBIE/TO-DO 3-column-preview-card-component-main/3-column-preview-card-component-main/styless.css
> +  --paragraphs: hsla(0, 0%, 100%, 0.75);
es mejor usar nombre de la variable que identifique el color y no su uso, porque este color también se podría usar en elementos que no son parrafos

2023-02-28 00:46 UTC, reidid commented on NEWBIE/TO-DO 3-column-preview-card-component-main/3-column-preview-card-component-main/styless.css
> +.card-1__img{
se puede utilizar un selector que combine el html sin necesidad de asingar la clase, algo como .card-1 img {  } que lo que indicaría es una imagen que esté adentro de un elemento que tiene la clase .card-1. Abajo hay más selectores como este

2023-02-28 00:46 UTC, reidid commented on NEWBIE/TO-DO 3-column-preview-card-component-main/3-column-preview-card-component-main/styless.css
> +.card-2 {
los estilos que se repiten se pueden usar en el mismo selector, no hay necesidad de crear un selector que hace lo mismo que otro. se crea un grupo de propiedades y se asignan a todos los elementos que apliquen los mismos estilos. Lo mismo para card1 2 y 3

2023-02-28 00:46 UTC, reidid commented on NEWBIE/TO-DO 3-column-preview-card-component-main/3-column-preview-card-component-main/styless.css
> +    display:flex;
esta clase ya es display flex, en el @media se incluyen solo las propiedades que se modifican

2023-03-01 20:19 UTC, closed without merging