Dev project portfolio
Semillero-Sincosoft/Workouts pull request #16
Opened 2023-02-27 17:44 UTC by elyato

finalizacion de proyecto pero tengo dudas que es en cierta medida del resposive se corta un poco el backgraund del footer y header me podrian recomendar soluciones para eso :c tuve ciertos problemas con las medidas pero pues viendo trabajos anteriores pude encontrar la solución

2023-02-28 01:04 UTC, reidid requested changes

2023-02-28 01:04 UTC, didierymartinez commented on NEWBIE/TO-DO project-portfolio/portfolio.html
> +        <section class="content-networks">
content-networks? por qué ese nombre de clase?

2023-02-28 01:04 UTC, didierymartinez commented on NEWBIE/TO-DO project-portfolio/portfolio.html
> +                En esta pagina puedes encontrar herramientras que te ayudaran
Ortografía

2023-02-28 01:04 UTC, didierymartinez commented on NEWBIE/TO-DO project-portfolio/portfolio.html
> +              <p>un diseñor para una marca conocida</p>
diseñor?

2023-02-28 01:04 UTC, didierymartinez commented on NEWBIE/TO-DO project-portfolio/portfolio.css
> +  --black-color: black;
no hay necesidad de crear una variable, black is black, a menos que se use como primario, secundario etc

2023-02-28 01:04 UTC, didierymartinez commented on NEWBIE/TO-DO project-portfolio/portfolio.css
> +  --primary-color: (#fbfbfb;);
por qué entre parentesis?

2023-02-28 01:04 UTC, didierymartinez commented on NEWBIE/TO-DO project-portfolio/portfolio.css
> +  width: 1200px;
este ancho está como raro, si el dispositivo es mayor se cortaría? o es muy grande

2023-02-28 01:04 UTC, reidid commented on NEWBIE/TO-DO project-portfolio/portfolio.css
> +.img-perfil {
es de tipo img mejor ahcer un selector por img.perfil

2023-02-28 01:04 UTC, reidid commented on NEWBIE/TO-DO project-portfolio/portfolio.css
> +.xd {
de nuevo? 20.000 pesos por cada clase xd que le encuentre

2023-02-28 01:04 UTC, reidid commented on NEWBIE/TO-DO project-portfolio/portfolio.css
> +svg {
todos los svg de la página siempre tendrían este tamaño sin importar el uso

2023-02-28 19:27 UTC, elyato commented on NEWBIE/TO-DO project-portfolio/portfolio.html
> +        <section class="content-networks">
para ser honesto lo copié,

2023-02-28 19:28 UTC, elyato commented on NEWBIE/TO-DO project-portfolio/portfolio.html
> +                En esta pagina puedes encontrar herramientras que te ayudaran
corregido, he hecho planas.

2023-02-28 19:28 UTC, elyato commented on NEWBIE/TO-DO project-portfolio/portfolio.html
> +              <p>un diseñor para una marca conocida</p>
corregido

2023-02-28 19:29 UTC, elyato commented on NEWBIE/TO-DO project-portfolio/portfolio.css
> +  --black-color: black;
ok corregido

2023-02-28 19:29 UTC, elyato commented on NEWBIE/TO-DO project-portfolio/portfolio.css
> +  --primary-color: (#fbfbfb;);
copiado

2023-02-28 19:31 UTC, elyato commented on NEWBIE/TO-DO project-portfolio/portfolio.css
> +  width: 1200px;
me toca dejarlo así

2023-02-28 19:35 UTC, elyato commented on NEWBIE/TO-DO project-portfolio/portfolio.css
> +.xd {
la eliminé porque no la uso se nota solo copié y pegué, pero no lo vuelvo a hacer

2023-02-28 19:35 UTC, elyato commented on NEWBIE/TO-DO project-portfolio/portfolio.css
> +.img-perfil {
sisas, me falta corregir

2023-02-28 19:37 UTC, elyato commented on NEWBIE/TO-DO project-portfolio/portfolio.css
> +svg {
pendiente

2023-02-28 21:25 UTC, elyato commented on NEWBIE/TO-DO project-portfolio/portfolio.css
> +.img-perfil {
breves ya se soluciono señor didier

2023-02-28 21:26 UTC, elyato commented on NEWBIE/TO-DO project-portfolio/portfolio.css
> +svg {
listo lo arregle acomodando los svg  del contenedor que necesito ejemplo: footer svg{
}

2023-03-01 20:15 UTC, didierymartinez approved these changes

2023-03-01 20:16 UTC, merged