Dev nsrp article previ
Semillero-Sincosoft/Workouts pull request #17
Opened 2023-02-27 21:49 UTC by Santiago1R

- Debo mejorar la metodología de nombramiento de las clases
- La organización del código debe de ser pulida 
- Practicar el uso de selectores, fuera de los comunes y usados en este ejercicio 
- Practicar el uso de hover y formas de posicionamiento absolute y relative

2023-03-01 20:33 UTC, reidid requested changes

2023-03-01 20:33 UTC, reidid commented on .vscode/settings.json
> +{
Este archivo no va en el repositorio (por ahora)

2023-03-01 20:33 UTC, reidid commented on NEWBIE/TO-DO 3-column-preview-card-component-main/3-column-preview-card-component-main/index.html
> +      <img src="/NEWBIE/TO-DO 3-column-preview-card-component-main/3-column-preview-card-component-main/images/icon-suvs.svg" alt="">
no dejar código comentareado, mejor eliminarlo

2023-03-01 20:33 UTC, reidid commented on NEWBIE/TO-DO 3-column-preview-card-component-main/styless.css
> +  --paragraphs: hsla(0, 0%, 100%, 0.75);
no crear con nombres de elementos

2023-03-01 20:33 UTC, reidid commented on NEWBIE/TO-DO article-preview-component-master/styless.css
> +  font-family: var(--font-family-import);
si hay una sola fuente de letra mejor no asignarla a una variable y colocarla en un elemento principal html o body

2023-03-01 20:33 UTC, reidid commented on NEWBIE/TO-DO article-preview-component-master/styless.css
> +.SHARE{
css en minuscula

2023-03-01 20:33 UTC, reidid commented on NEWBIE/TO-DO article-preview-component-master/styless.css
> +.Triangle-hov{
minusculas y separados por -

2023-03-01 20:33 UTC, reidid commented on NEWBIE/TO-DO article-preview-component-master/styless.css
> +    display: flex;
container ya es flex no hay necesidad de colocar estas poropiedades en el @media, solo las que cambian

2023-03-07 20:38 UTC, reidid approved these changes

2023-03-07 21:55 UTC, Santiago1R commented on NEWBIE/TO-DO 3-column-preview-card-component-main/styless.css
> +  --paragraphs: hsla(0, 0%, 100%, 0.75);
solucionado

2023-03-07 21:55 UTC, Santiago1R commented on NEWBIE/TO-DO article-preview-component-master/styless.css
> +.SHARE{
solucionado

2023-03-07 21:55 UTC, Santiago1R commented on NEWBIE/TO-DO article-preview-component-master/styless.css
> +.Triangle-hov{
solucionado

2023-03-07 21:55 UTC, Santiago1R commented on NEWBIE/TO-DO article-preview-component-master/styless.css
> +    display: flex;
solucionado

2023-03-07 21:56 UTC, Santiago1R commented on NEWBIE/TO-DO article-preview-component-master/styless.css
> +  font-family: var(--font-family-import);
solucionado

2023-04-04 14:37 UTC, reidid approved these changes

2023-06-27 16:58 UTC, merged