Dev cl calculator
Semillero-Sincosoft/Workouts pull request #40
Opened 2023-04-26 14:45 UTC by elyato

Este ejercicio estuvo complicado porque no  teníamos el suficiente conocimiento entonces tuvimos que estudiar para encontrar la solución lo que fue css y html no se me complico  pero pues logramos sacarlo adelante

2023-04-28 14:26 UTC, reidid commented on NEWBIE/TODO tip-calculator-app-main/calculator.js
> +    calculateBill(
Esta función también puede estar en otro módulo ya que se repite y los parse se pueden hacer adentro de la función, inclusive la asignación del valor

2023-04-28 14:26 UTC, reidid commented on NEWBIE/TODO tip-calculator-app-main/variablesGlobals.js
en inglés es global variables

2023-04-28 14:26 UTC, reidid commented on NEWBIE/TODO tip-calculator-app-main/funciones.js
> +export function eventButton() {
cuál button, el nombre de la función podría aplicar a cualquier botón, por lo cual no es un nombre descriptivo

2023-04-28 14:26 UTC, reidid commented on NEWBIE/TODO tip-calculator-app-main/funciones.js
> +      console.log(tipvalue);
no dejar console en el código, para esto están los puntos de interrupción y las herramientas de depuración

2023-04-28 14:26 UTC, reidid commented on NEWBIE/TODO tip-calculator-app-main/funciones.js
> +      let tipvalue = e.target.innerText.replace("%", "");
puede ser const si no se modifica el valor

2023-04-28 14:26 UTC, reidid commented on NEWBIE/TODO tip-calculator-app-main/funciones.js
> +      if (intoBill.value === "") {
esta validación se puede declarar en otra función y modularizar

2023-04-28 14:26 UTC, reidid commented on NEWBIE/TODO tip-calculator-app-main/funciones.js
> +  let tipAmount = (intoBill * (tipPercentage / 100)) / numberPeople;
(tipPercentage / 100) esta división sería más adecuado hacerla al asignar el valor a tipPercentage, porque ya queda asignado un porcentaje y así se llama la variable. Línea 24,

en esta línea sería solo multiplicar por porcetaje de propina
si se divide sobre el número de personas ya no es tipAmout es tipAmountPerPerson

2023-04-28 14:26 UTC, reidid commented on NEWBIE/TODO tip-calculator-app-main/funciones.js
> +  let totalAmount = intoBill / numberPeople + tipAmount;
lo mismo, totalAmount per person

2023-04-28 14:26 UTC, reidid requested changes
Por favor resolver comentarios que dejé

2023-04-28 14:33 UTC, elyato commented on NEWBIE/TODO tip-calculator-app-main/funciones.js
> +      console.log(tipvalue);
listo ya se corrigió este error señor Didider

2023-04-28 14:53 UTC, elyato commented on NEWBIE/TODO tip-calculator-app-main/variablesGlobals.js
ya le cambie el nombre :3

2023-04-28 15:29 UTC, elyato commented on NEWBIE/TODO tip-calculator-app-main/funciones.js
> +export function eventButton() {
LISTO creo que le puse un nombre  mas apropiado

2023-05-02 15:08 UTC, elyato commented on NEWBIE/TODO tip-calculator-app-main/funciones.js
> +  let tipAmount = (intoBill * (tipPercentage / 100)) / numberPeople;
listo señor Didier  realizado

2023-05-02 15:09 UTC, elyato commented on NEWBIE/TODO tip-calculator-app-main/calculator.js
> +    calculateBill(
Listo esto ya lo hice pero lo de los valores no supe como hacerlo me podría dar un consejo para realizarlo bien

2023-05-02 17:11 UTC, elyato commented on NEWBIE/TODO tip-calculator-app-main/funciones.js
> +      if (intoBill.value === "") {
listo señor didier

2023-05-02 17:12 UTC, elyato commented on NEWBIE/TODO tip-calculator-app-main/funciones.js
> +  let totalAmount = intoBill / numberPeople + tipAmount;
esta también esta

2023-05-08 13:38 UTC, reidid approved these changes

2023-05-08 13:39 UTC, merged