Dev nsrp tip calculator
Semillero-Sincosoft/Workouts pull request #41
Opened 2023-04-26 14:46 UTC by Santiago1R

- Se presento dificultad para la realización de este ejercicio. Pero con estudio pudimos lograr comprender y llegar a soluciones para poder completarlo
- Fue fácil realizar el HTML y el CSS. Fue lo que menos tiempo nos tomo
- en este ejercicio aprendimos a refactorizar y modular 
- este ejercicio lo voy a volver a realizar en un tiempo para ver el progreso de los conocimientos y habilidades

2023-04-28 14:34 UTC, reidid reviewed
No realizar un commit con todos los archivos, es confuso revisar los js junto con las imagenes, md etc, se pueden hacer commits separados

2023-04-28 14:34 UTC, reidid commented on NEWBIE/TODO tip-calculator-app-main/variables.js
no son variables como tal, son elementos HTML ya que un archivo nombrado como variables es muy generico y no describe qué valores puede tener adentro

2023-04-28 14:34 UTC, reidid commented on NEWBIE/TODO tip-calculator-app-main/metodos.js
qué diferencia tiene este archivo con el otro que se llama funciones, por qué metodos y el otro funciones?

2023-04-28 14:42 UTC, reidid requested changes

2023-04-28 14:42 UTC, reidid commented on NEWBIE/TODO tip-calculator-app-main/metodos.js
> +    if (intoBill.value === "") return;
es mejor dejar los {} después de los if, if (intoBill.value === "")  { return; }, inclusive si es solo una línea ya que alguien puede llegar y colocar código debajo y no notar que es un fragmento de código

2023-04-28 14:42 UTC, reidid commented on NEWBIE/TODO tip-calculator-app-main/metodos.js
> +      parseFloat(intoBill.value),
la función calculateTip tiene acceso a la variable intoBill entonces podría hacerse allá esta línea y se haría en un solo lugar, y no sería pasar el valor como parámetro, lo mismo para numberOfPeople

2023-04-28 14:42 UTC, reidid commented on NEWBIE/TODO tip-calculator-app-main/metodos.js
> +      alert("Ingrese valores");
es recomendable indicarle al usuario cuáles valores debe ingresar, los alert ya están un poco antiguos

2023-05-02 16:08 UTC, Santiago1R commented on NEWBIE/TODO tip-calculator-app-main/metodos.js
> +      parseFloat(intoBill.value),
Solucionado.

2023-05-02 16:08 UTC, Santiago1R commented on NEWBIE/TODO tip-calculator-app-main/metodos.js
> +    if (intoBill.value === "") return;
Solucionado.

2023-05-02 16:11 UTC, Santiago1R commented on NEWBIE/TODO tip-calculator-app-main/metodos.js
> +    if (intoBill.value === "") return;
Solucionado.

2023-05-02 16:11 UTC, Santiago1R commented on NEWBIE/TODO tip-calculator-app-main/metodos.js
> +      parseFloat(intoBill.value),
Solucionado.

2023-05-02 16:15 UTC, Santiago1R commented on NEWBIE/TODO tip-calculator-app-main/variables.js
Solucionado, ya cambie el nombre

2023-05-02 16:40 UTC, Santiago1R commented on NEWBIE/TODO tip-calculator-app-main/metodos.js
Fue error mío el colocar esos nombres, la diferencia entre una función y un método, es que el método esta asociado con un objeto. Por ende, los nombres en este caso no son aplicables. Ya los cambié.

2023-05-02 19:51 UTC, Santiago1R commented on NEWBIE/TODO tip-calculator-app-main/metodos.js
> +      alert("Ingrese valores");
Lo solucione de manera que cuando se de enter sin tener un valor para poder hacer la operación, al input se le aplicara un borde rojo con un mensaje de "error %"

2023-05-08 13:40 UTC, didierymartinez approved these changes

2023-05-08 13:40 UTC, merged